[[normalDict]]
org = "‘"
rep = "“"
isReg = false
priority = 0

[[normalDict]]
org = "’"
rep = "”"
isReg = false
priority = 0

[[normalDict]]
org = ","
rep = "，"
isReg = false
priority = 0

[[normalDict]]
org = "?"
rep = "？"
isReg = false
priority = 0

[[normalDict]]
org = "!"
rep = "！"
isReg = false
priority = 0

[[normalDict]]
org = "~"
rep = "～"
isReg = false
priority = 0

[[normalDict]]
org = "&"
rep = "＆"
isReg = false
priority = 0

[[normalDict]]
org = "・"
rep = "·"
isReg = false
priority = 0

[[normalDict]]
org = "ー"
rep = "—"
isReg = false
priority = 0

[[normalDict]]
org = "—"
rep = "——"
isReg = false
priority = 0

[[normalDict.conditions]]
conditionReg = "\\A(?![\\S\\s]*——)"
conditionTarget = "transraw"

[[normalDict]]
org = "『"
rep = "《"
isReg = false
priority = 0

[[normalDict.conditions]]
conditionReg = "《"
conditionTarget = "orig"

[[normalDict]]
org = "』"
rep = "》"
isReg = false
priority = 0

[[normalDict.conditions]]
conditionReg = "》"
conditionTarget = "orig"

[[normalDict]]
org = "《"
rep = "『"
isReg = false
priority = 0

[[normalDict.conditions]]
conditionReg = "『"
conditionTarget = "orig"

[[normalDict]]
org = "》"
rep = "』"
isReg = false
priority = 0

[[normalDict.conditions]]
conditionReg = "』"
conditionTarget = "orig"

[[normalDict]]
org = "“"
rep = "「"
isReg = false
priority = 0

[[normalDict.conditions]]
conditionReg = "「"
conditionTarget = "preproc"

[[normalDict]]
org = "”"
rep = "」"
isReg = false
priority = 0

[[normalDict.conditions]]
conditionReg = "」"
conditionTarget = "preproc"

[[normalDict]]
org = "‘"
rep = "『"
isReg = false
priority = 0

[[normalDict.conditions]]
conditionReg = "『"
conditionTarget = "preproc"

[[normalDict]]
org = "’"
rep = "』"
isReg = false
priority = 0

[[normalDict.conditions]]
conditionReg = "』"
conditionTarget = "preproc"

[[normalDict]]
org = "“"
rep = "『"
isReg = false
priority = 0

[[normalDict.conditions]]
conditionReg = "『"
conditionTarget = "preproc"

[[normalDict]]
org = "”"
rep = "』"
isReg = false
priority = 0

[[normalDict.conditions]]
conditionReg = "』"
conditionTarget = "preproc"

[[normalDict]]
org = "『"
rep = "“"
isReg = false
priority = 0

[[normalDict.conditions]]
conditionReg = "“"
conditionTarget = "orig"

[[normalDict]]
org = "』"
rep = "”"
isReg = false
priority = 0

[[normalDict.conditions]]
conditionReg = "”"
conditionTarget = "orig"

[[normalDict]]
org = "《"
rep = "“"
isReg = false
priority = 0

[[normalDict.conditions]]
conditionReg = "“"
conditionTarget = "orig"

[[normalDict]]
org = "》"
rep = "”"
isReg = false
priority = 0

[[normalDict.conditions]]
conditionReg = "”"
conditionTarget = "orig"

[[normalDict]]
org = "‘"
rep = "“"
isReg = false
priority = 0

[[normalDict.conditions]]
conditionReg = "“"
conditionTarget = "orig"

[[normalDict]]
org = "’"
rep = "”"
isReg = false
priority = 0

[[normalDict.conditions]]
conditionReg = "”"
conditionTarget = "orig"

[[normalDict]]
org = "。。"
rep = "。"
isReg = false
priority = 0

[[normalDict.conditions]]
conditionReg = "\\A(?![\\S\\s]*。。)"
conditionTarget = "orig"

