[[normalDict]]
org = '筿'
rep = '篠'
isReg = false
priority = 0

[[normalDict]]
org = '荘'
rep = '庄'
isReg = false
priority = 0

[[normalDict]]
org = '滝'
rep = '泷'
isReg = false
priority = 0

[[normalDict]]
org = '囧'
rep = '窘'
isReg = false
priority = 0

[[normalDict]]
org = '樫'
rep = '㭴'
isReg = false
priority = 0

[[normalDict]]
org = '纮'
rep = '弦'
isReg = false
priority = 0

[[normalDict]]
org = '偾'
rep = '喷'
isReg = false
priority = 0

[[normalDict]]
org = '哕'
rep = '呕'
isReg = false
priority = 0

[[normalDict]]
org = '憐'
rep = '怜'
isReg = false
priority = 0

[[normalDict]]
org = '穂'
rep = '穗'
isReg = false
priority = 0

[[normalDict]]
org = '砕'
rep = '碎'
isReg = false
priority = 0

[[normalDict]]
org = '粋'
rep = '粹'
isReg = false
priority = 0

[[normalDict]]
org = '桜'
rep = '樱'
isReg = false
priority = 0

[[normalDict]]
org = '長'
rep = '长'
isReg = false
priority = 0

[[normalDict]]
org = '茑'
rep = '鸟'
isReg = false
priority = 0

[[normalDict]]
org = '菫'
rep = '堇'
isReg = false
priority = 0

[[normalDict]]
org = '嗻'
rep = '呜'
isReg = false
priority = 0

[[normalDict]]
org = '掻'
rep = '搔'
isReg = false
priority = 0

[[normalDict]]
org = '妳'
rep = '你'
isReg = false
priority = 0

