[[normalDict]]
org = '‘'
rep = '“'
isReg = false
priority = 0

[[normalDict]]
org = '’'
rep = '”'
isReg = false
priority = 0

[[normalDict]]
org = ','
rep = '，'
isReg = false
priority = 0

[[normalDict]]
org = '?'
rep = '？'
isReg = false
priority = 0

[[normalDict]]
org = '!'
rep = '！'
isReg = false
priority = 0

[[normalDict]]
org = '~'
rep = '～'
isReg = false
priority = 0

[[normalDict]]
org = '&'
rep = '＆'
isReg = false
priority = 0

[[normalDict]]
org = '・'
rep = '·'
isReg = false
priority = 0

[[normalDict]]
org = 'ー'
rep = '—'
isReg = false
priority = 0

[[normalDict]]
org = '—'
rep = '——'
conditions = [{ conditionTarget = 'transraw', conditionReg = '\A(?![\S\s]*——)' }]
isReg = false
priority = 0

[[normalDict]]
org = '『'
rep = '《'
conditions = [{ conditionTarget = 'orig', conditionReg = '《' }]
isReg = false
priority = 0

[[normalDict]]
org = '』'
rep = '》'
conditions = [{ conditionTarget = 'orig', conditionReg = '》' }]
isReg = false
priority = 0

[[normalDict]]
org = '《'
rep = '『'
conditions = [{ conditionTarget = 'orig', conditionReg = '『' }]
isReg = false
priority = 0

[[normalDict]]
org = '》'
rep = '』'
conditions = [{ conditionTarget = 'orig', conditionReg = '』' }]
isReg = false
priority = 0

[[normalDict]]
org = '“'
rep = '「'
conditions = [{ conditionTarget = 'preproc', conditionReg = '「' }]
isReg = false
priority = 0

[[normalDict]]
org = '”'
rep = '」'
conditions = [{ conditionTarget = 'preproc', conditionReg = '」' }]
isReg = false
priority = 0

[[normalDict]]
org = '‘'
rep = '『'
conditions = [{ conditionTarget = 'preproc', conditionReg = '『' }]
isReg = false
priority = 0

[[normalDict]]
org = '’'
rep = '』'
conditions = [{ conditionTarget = 'preproc', conditionReg = '』' }]
isReg = false
priority = 0

[[normalDict]]
org = '“'
rep = '『'
conditions = [{ conditionTarget = 'preproc', conditionReg = '『' }]
isReg = false
priority = 0

[[normalDict]]
org = '”'
rep = '』'
conditions = [{ conditionTarget = 'preproc', conditionReg = '』' }]
isReg = false
priority = 0

[[normalDict]]
org = '『'
rep = '“'
conditions = [{ conditionTarget = 'orig', conditionReg = '“' }]
isReg = false
priority = 0

[[normalDict]]
org = '』'
rep = '”'
conditions = [{ conditionTarget = 'orig', conditionReg = '”' }]
isReg = false
priority = 0

[[normalDict]]
org = '《'
rep = '“'
conditions = [{ conditionTarget = 'orig', conditionReg = '“' }]
isReg = false
priority = 0

[[normalDict]]
org = '》'
rep = '”'
conditions = [{ conditionTarget = 'orig', conditionReg = '”' }]
isReg = false
priority = 0

[[normalDict]]
org = '‘'
rep = '“'
conditions = [{ conditionTarget = 'orig', conditionReg = '“' }]
isReg = false
priority = 0

[[normalDict]]
org = '’'
rep = '”'
conditions = [{ conditionTarget = 'orig', conditionReg = '”' }]
isReg = false
priority = 0

[[normalDict]]
org = '。。'
rep = '。'
conditions = [{ conditionTarget = 'orig', conditionReg = '\A(?![\S\s]*。。)' }]
isReg = false
priority = 0

