[plugins.Epub]
bilingualOutput = true        # 默认输出双语文件。
originalTextColor = "#808080" # 原文默认颜色。
originalTextScale = 0.8       # 原文默认缩放比例。

# 正则语法见 BaseConfig/illustration/epub.html。
[[plugins.Epub.preprocRegex]]
org = '<ruby><rb>(.+?)</rb><rt>(.+?)</rt></ruby>'
rep = '[$2/$1]'

[[plugins.Epub.preprocRegex]]
org = '(<p[^>/]*>)(.*?)(</p>)'
callback = [
 { org = '<[^>]*>', rep = '', group = 2 },
]

[[plugins.Epub.postprocRegex]]
org = '\[([^/\[\]]+?)/([^/\[\]]+?)\]'
rep = '<ruby><rb>$2</rb><rt>$1</rt></ruby>'
