[plugins.Epub]
"双语显示" = true      # 默认开启双语显示
"原文颜色" = "#808080" # 默认灰色
"缩小比例" = 0.8       # 默认缩小到原始大小的80%
"预处理正则" = [
	{ org = '''<ruby><rb>(.+?)</rb><rt>(.+?)</rt></ruby>''', rep = '''[$2/$1]''' },
]
"后处理正则" = [
	{ org = '''\[([^/\[\]]+?)/([^/\[\]]+?)\]''', rep = '''<ruby><rb>$2</rb><rt>$1</rt></ruby>''' },
]