[workspace]
members = ["GalTranslPP", "GPPVersion", "GPPCLI", "GPPGUI", "Updater"]

[workspace.package]
version = "3.1.2"
standard = "c++23"
license = "Apache-2.0"

[toolchain]
windows = "llvm@22.1.8"

[workspace.build]
cxx_runtime = "host-coupled"
cxxflags = [
  "-finput-charset=UTF-8",
  "-fexec-charset=UTF-8"
]
defines = [
  "SPDLOG_COMPILED_LIB",
  "PROJECT_NO_ANSI",
]
