[workspace]
members = ["GalTranslPP", "GPPVersion", "GPPCLI", "GPPGUI", "Updater"]

[workspace.package]
version = "3.2.3"
standard = "c++23"
license = "LicenseRef-GalTranslPP"

[workspace.toolchain]
windows = "llvm@23.1.3"

[workspace.build]
cxx_runtime = "host-coupled"
cxxflags = [
  "-finput-charset=UTF-8",
  "-fexec-charset=UTF-8"
]
defines = [
  "ABSL_CONSUME_DLL",
  "SPDLOG_COMPILED_LIB",
  "SPDLOG_SHARED_LIB",
  "FMT_SHARED",
  "PROJECT_NO_ANSI",
]

[workspace.target.windows.build]
defines = ["UNICODE", "_UNICODE", "_CRT_SECURE_NO_WARNINGS",
  "WIN32_LEAN_AND_MEAN", "NOMINMAX",
  # 详见 https://github.com/microsoft/STL/issues/6121，https://developercommunity.visualstudio.com/t/11148844
  "_RANGES_",
  "SPDLOG_WCHAR_FILENAMES"]

[workspace.profile.release]
opt = 3
debug = true
lto = true

[workspace.profile.fast-release]
opt = 0
debug = true
lto = false
