[package]
namespace = "gpp"
name = "gui"

[dependencies]
"gpp.core" = { path = "../GalTranslPP" }
"gpp.version" = { path = "../GPPVersion" }
"gpp.updater" = { path = "../Updater", artifacts = ["Updater"] }

[build-dependencies]
"gpp.build" = { path = "../mcpp-build-scripts/gpp-build", host-module = true }

[target.windows.build-dependencies]
"gpp.vcpkg-link-libs" = { path = "../mcpp-build-scripts/vcpkg-link-libs", tools = ["vcpkg_link_libs"] }
"gpp.runtime-stage" = { path = "../mcpp-build-scripts/runtime-stage", tools = ["runtime_stage"] }

[profile.release]
opt = 3
debug = true
lto = true

[profile.fast-release]
opt = 0
debug = true
lto = false

[build]
default-profile = "release"
sources = [
  "*.cpp",
  "TreeSitterGrammars/**/*.c",
  "!GPPGUI.cpp",
  "!x64/**",
  "!x86/**"
]

[target.windows.build]
defines = ["UNICODE", "_UNICODE",
  "WIN32_LEAN_AND_MEAN", "NOMINMAX", "_CRT_SECURE_NO_WARNINGS",
  "_RANGES_",
  "SPDLOG_WCHAR_FILENAMES"]
ldflags = ["-ldbghelp"]

[targets.GalTranslPP_GUI]
kind = "bin"
main = "GPPGUI.cpp"
windows_subsystem = "windows"

[resources]
files = ["GPPGUI.rc"]
extra-inputs = ["GPPGUI.manifest", "Resource/images/julixian_s.ico"]
