#include "ProjectCachePage.h"
#include "ProjectCachePage_p.h"

#include <algorithm>
#include <fstream>

#include <QCollator>
#include <QFileInfo>
#include <QItemSelectionModel>
#include <QStandardItem>

#include "ElaListView.h"
#include "ElaPushButton.h"
#include "ElaText.h"

import Tool;

using namespace ProjectCachePagePrivate;

void ProjectCachePage::_loadCacheFiles()
{
    _cacheFiles.clear();
    const fs::path cacheDir = _cacheDir();
    if (!fs::exists(cacheDir)) {
        std::error_code ec;
        fs::create_directories(cacheDir, ec);
    }

    if (fs::exists(cacheDir)) {
        for (const auto& entry : fs::recursive_directory_iterator(cacheDir)) {
            if (!entry.is_regular_file() || entry.path().extension() != L".json") {
                continue;
            }
            CacheFileInfo info;
            info.relativeName = QString(fs::relative(entry.path(), cacheDir).generic_wstring());
            std::error_code ec;
            info.size = entry.file_size(ec);
            QFileInfo fileInfo(QString(entry.path().wstring()));
            info.modified = fileInfo.lastModified();

            nlohmann::json data;
            QString error;
            if (_readCacheFile(info.relativeName, data, &error) && data.is_array()) {
                info.entries = (int)data.size();
                for (const auto& item : data) {
                    if (item.is_object() && !_problemString(item).isEmpty()) {
                        ++info.problems;
                    }
                }
            }
            else {
                info.parseOk = false;
                info.error = error;
            }
            _cacheFiles.push_back(info);
        }
    }

    QCollator collator;
    collator.setNumericMode(true);
    collator.setCaseSensitivity(Qt::CaseInsensitive);
    // Match Windows Explorer's natural ordering, e.g. 1, 2, 10 instead of 1, 10, 2.
    std::sort(_cacheFiles.begin(), _cacheFiles.end(), [&collator](const CacheFileInfo& a, const CacheFileInfo& b)
        {
            return collator.compare(a.relativeName, b.relativeName) < 0;
        });

    _cacheDirLabel->setText(QString(cacheDir.wstring()));
    _renderFileList();
    _loadProblems();
    _runGlobalSearch();
    _updateActionStates();
}

void ProjectCachePage::_renderFileList()
{
    _fileModel->clear();
    for (const CacheFileInfo& file : _cacheFiles) {
        QString title = file.relativeName;
        if (_dirtyFiles.contains(file.relativeName)) {
            title = "*" + title;
        }
        QString subtitle = tr("%1 句 · %2 问题").arg(file.entries).arg(file.problems);
        if (!file.parseOk) {
            subtitle = tr("解析失败");
        }
        QStandardItem* item = new QStandardItem(title + "\n" + subtitle);
        item->setData(file.relativeName, Qt::UserRole);
        item->setToolTip(file.parseOk ? file.relativeName : file.error);
        item->setEditable(false);
        setModelItemFont(item, BodyFontPx);
        _fileModel->appendRow(item);
        if (_currentFile == file.relativeName) {
            const QModelIndex index = _fileModel->indexFromItem(item);
            _fileList->selectionModel()->select(index, QItemSelectionModel::ClearAndSelect | QItemSelectionModel::Rows);
            _fileList->setCurrentIndex(index);
        }
    }
    if (_filesNavButton) {
        _filesNavButton->setText(tr("文件 (%1)").arg(_cacheFiles.size()));
    }
}

void ProjectCachePage::_loadCacheFile(const QString& filename, bool forceReload)
{
    if (filename.isEmpty()) {
        return;
    }
    const bool fileChanged = _currentFile != filename;
    if (!forceReload && _loadedEntriesByFile.contains(filename)) {
        _entries = _loadedEntriesByFile.value(filename);
    }
    else {
        QString error;
        if (!_readCacheFile(filename, _entries, &error)) {
            _setError(error);
            return;
        }
        if (!_entries.is_array()) {
            _setError(tr("缓存文件不是 JSON 数组: ") + filename);
            return;
        }
        _loadedEntriesByFile[filename] = _entries;
    }
    _currentFile = filename;
    if (fileChanged) {
        _selectedEntryRows.clear();
    }
    _currentFileLabel->setText((_dirtyFiles.contains(filename) ? "*" : "") + filename);
    _renderEntries();
    _updateCurrentSummary();
    _updateActionStates();
}

fs::path ProjectCachePage::_cacheDir() const
{
    return _projectDir / transCacheDirName;
}

fs::path ProjectCachePage::_cachePathForRelativeName(const QString& filename) const
{
    return _cacheDir() / fs::path(filename.toStdWString());
}

bool ProjectCachePage::_readCacheFile(const QString& filename, nlohmann::json& entries, QString* errorMessage) const
{
    try {
        // Cache files are UTF-8 JSON arrays generated by the translator core.
        std::ifstream ifs(_cachePathForRelativeName(filename), std::ios::binary);
        if (!ifs.is_open()) {
            if (errorMessage) {
                *errorMessage = tr("无法打开缓存文件: ") + filename;
            }
            return false;
        }
        entries = nlohmann::json::parse(ifs);
        return true;
    }
    catch (const std::exception& e) {
        if (errorMessage) {
            *errorMessage = tr("解析缓存失败: ") + filename + "\n" + QString::fromStdString(e.what());
        }
        return false;
    }
}

bool ProjectCachePage::_writeCacheFile(const QString& filename, const nlohmann::json& entries, QString* errorMessage) const
{
    try {
        const fs::path path = _cachePathForRelativeName(filename);
        createParent(path);
        std::ofstream ofs(path, std::ios::binary | std::ios::trunc);
        if (!ofs.is_open()) {
            if (errorMessage) {
                *errorMessage = tr("无法写入缓存文件: ") + filename;
            }
            return false;
        }
        ofs << entries.dump(2);
        return true;
    }
    catch (const std::exception& e) {
        if (errorMessage) {
            *errorMessage = tr("写入缓存失败: ") + filename + "\n" + QString::fromStdString(e.what());
        }
        return false;
    }
}

