[package]
namespace = "gpp"
name = "updater"

[dependencies]
"gpp.version" = { path = "../GPPVersion" }

[build-dependencies]
"gpp.runtime-stage" = { path = "../mcpp-build-scripts/runtime-stage", tools = ["runtime_stage"] }

[profile.release]
opt = 3
debug = false
lto = true
strip = false
ldflags = ["-Wl,/OPT:REF", "-Wl,/OPT:ICF", "-Wl,/INCREMENTAL:NO"]

[profile.fast-release]
opt = 0
debug = false
lto = false
strip = false

[build]
default-profile = "release"
include_dirs = [
  ".",
  "../vcpkg_installed/gpp-x64-windows-release/include"
]
ldflags = [
  "-luser32",
  "-loleaut32"
]

[targets.Updater]
kind = "bin"
main = "Updater.cpp"
windows_subsystem = "windows"

[resources]
files = ["Updater.rc"]
extra-inputs = ["Updater.manifest"]
