[package]
namespace = "gpp"
name = "updater"

[dependencies]
"gpp.version" = { path = "../GPPVersion" }

[build-dependencies]
"gpp.build" = { path = "../mcpp-build-scripts/gpp-build", host-module = true }

[target.windows.build-dependencies]
"gpp.runtime-stage" = { path = "../mcpp-build-scripts/runtime-stage", tools = ["runtime_stage"] }

[profile.release]
opt = 3
debug = true
lto = true

[profile.fast-release]
opt = 0
debug = true
lto = false

[build]
default-profile = "release"
# sources = [
#   "../3rdParty/3rdModule/boost.ixx"
# ]
# module_extensions = [".ixx"]
include_dirs = ["."]

[target.windows.build]
defines = ["WIN32_LEAN_AND_MEAN", "NOMINMAX", "_CRT_SECURE_NO_WARNINGS", "SPDLOG_WCHAR_FILENAMES", "_RANGES_"]
ldflags = ["-luser32", "-loleaut32"]

[targets.Updater]
kind = "bin"
main = "Updater.cpp"
windows_subsystem = "windows"

[resources]
files = ["Updater.rc"]
extra-inputs = ["Updater.manifest"]
