[package]
namespace = "gpp"
name = "runtime-stage"
version = "1.0.0"
standard = "c++23"
license = "LicenseRef-GalTranslPP"

[build]
sources = []

[targets.runtime-stage]
kind = "bin"
main = "main.cpp"
