[package]
namespace = "gpp"
name = "runtime-stage"
version = "1.0.0"
standard = "c++23"
license = "Apache-2.0"

[toolchain]
windows = "llvm@22.1.8"

[build]
sources = []

[targets.runtime_stage]
kind = "bin"
main = "main.cpp"
