[package]
namespace = "gpp"
name = "version"

[build]
default-profile = "release"
sources = [
  "GPPVersion.ixx",
  "!x64/**",
  "!x86/**"
]
module_extensions = [".ixx"]

[target.windows.build]
defines = ["_LIB"]

[targets.GPPVersion]
kind = "lib"
