[[gptDict]]
note = ''
replaceStr = '责难'
searchStr = '責め'

[[gptDict]]
note = ''
replaceStr = '蛋蛋'
searchStr = 'キンタマ'

[[gptDict]]
note = ''
replaceStr = '嘴穴'
searchStr = '口まんこ'

[[gptDict]]
note = ''
replaceStr = '小穴'
searchStr = 'おめこ'

[[gptDict]]
note = ''
replaceStr = '小穴'
searchStr = 'おまんこ'

[[gptDict]]
note = ''
replaceStr = '小穴'
searchStr = 'まんこ'

[[gptDict]]
note = ''
replaceStr = '肉棒'
searchStr = 'おちんちん'

[[gptDict]]
note = ''
replaceStr = '肉棒'
searchStr = 'ちんちん'

[[gptDict]]
note = ''
replaceStr = '肉棒'
searchStr = 'おちんぽ'

[[gptDict]]
note = ''
replaceStr = '肉棒'
searchStr = 'ちんぽ'