allowCloseWhenRunning = false
allowMultiInstance = false
autoCheckUpdate = true
autoDownloadUpdate = true
autoRefreshAfterTranslate = true
clearLogShortcut = "Ctrl+L"
defaultDictOpenMode = 1
defaultNameTableOpenMode = 1
language = "zh_CN"
navigationMode = 0
projects = []
pythonEnvPath = "BaseConfig/Python-3.12.10-embed-amd64"
stackSwitchMode = 1
themeMode = 0
windowDisplayMode = 1
windowHeight = 675
windowPosX = 40
windowPosY = 51
windowWidth = 1366

[commonGptDicts]
dictNames = ["CommonGpt", "CommonGpt_H"]

[commonGptDicts.spec.CommonGpt]
defaultOn = true
openMode = 1

[commonGptDicts.spec.CommonGpt.columnWidth]
0 = 346
1 = 199
2 = 559

[commonGptDicts.spec.CommonGpt_H]
defaultOn = true
openMode = 1

[commonGptDicts.spec.CommonGpt_H.columnWidth]
0 = 360
1 = 215
2 = 425

[commonPostDicts]
dictNames = [
    "PostStd",
    "PostPunctuation",
    "PostRareCnChar",
    "PostPunctuation_GT",
]

[commonPostDicts.spec.PostStd]
defaultOn = true
openMode = 1

[commonPostDicts.spec.PostStd.columnWidth]
0 = 285
1 = 195
2 = 348
3 = 81
4 = 61
5 = 60

[commonPostDicts.spec.PostPunctuation]
defaultOn = true
openMode = 1

[commonPostDicts.spec.PostPunctuation.columnWidth]
0 = 285
1 = 136
2 = 409
3 = 81
4 = 65
5 = 60

[commonPostDicts.spec.PostRareCnChar]
defaultOn = true
openMode = 1

[commonPostDicts.spec.PostRareCnChar.columnWidth]
0 = 285
1 = 195
2 = 341
3 = 81
4 = 62
5 = 60

[commonPostDicts.spec.PostPunctuation_GT]
defaultOn = false
openMode = 1

[commonPostDicts.spec.PostPunctuation_GT.columnWidth]
0 = 285
1 = 195
2 = 344
3 = 78
4 = 66
5 = 60

[commonPreDicts]
dictNames = ["PreHUnify", "PreStutterCorrect"]

[commonPreDicts.spec.PreHUnify]
defaultOn = true
openMode = 1

[commonPreDicts.spec.PreHUnify.columnWidth]
0 = 285
1 = 195
2 = 349
3 = 81
4 = 70
5 = 60

[commonPreDicts.spec.PreStutterCorrect]
defaultOn = false
openMode = 1

[commonPreDicts.spec.PreStutterCorrect.columnWidth]
0 = 285
1 = 195
2 = 336
3 = 88
4 = 66
5 = 60

[showDockWidget]
302 = true

[[popularCards]]
cardFloatPixmap = ':/GPPGUI/Resource/images/IARC_7+.svg.png'
cardPixmap = ':/GPPGUI/Resource/images/satan53x.jpg'
detailedText = '从GalGame脚本提取和导入文本'
fromLocal = false
interactiveTips = 'Satan53x'
pathOrUrl = 'https://github.com/satan53x/SExtractor'
subTitle = '草佬味大，无需多盐'
title = 'SExTractor'

[[popularCards]]
cardFloatPixmap = ':/GPPGUI/Resource/images/IARC_7+.svg.png'
cardPixmap = ':/GPPGUI/Resource/images/gar.png'
detailedText = '神一样的解封包工具'
fromLocal = false
interactiveTips = 'morkt'
pathOrUrl = 'https://github.com/crskycode/GARbro'
subTitle = '无敌了'
title = 'GARbro'

[[popularCards]]
cardFloatPixmap = ':/GPPGUI/Resource/images/IARC_7+.svg.png'
cardPixmap = ':/GPPGUI/Resource/images/vnt.png'
detailedText = '萌新拯救者一般的文本提取与回封工具'
fromLocal = false
interactiveTips = 'arcusmaximus'
pathOrUrl = 'https://github.com/arcusmaximus/VNTranslationTools'
subTitle = '能少用就少用'
title = 'VNTranslationTools'

[[popularCards]]
cardFloatPixmap = ':/GPPGUI/Resource/images/IARC_7+.svg.png'
cardPixmap = ':/GPPGUI/Resource/images/crass.png'
detailedText = '早期Galgame解包工具，多看看它的说明文档'
fromLocal = false
interactiveTips = '痴漢公賊'
pathOrUrl = 'https://github.com/shangjiaxuan/Crass-source'
subTitle = '专治老游戏'
title = 'Crass'

[[popularCards]]
cardFloatPixmap = ':/GPPGUI/Resource/images/IARC_7+.svg.png'
cardPixmap = ':/GPPGUI/Resource/images/sublime.png'
detailedText = '高亮很好使，但编码转换不如emeditor'
fromLocal = false
interactiveTips = 'Sublime HQ'
pathOrUrl = 'https://www.sublimetext.com'
subTitle = '和Em互补长短'
title = 'Sublime'

[[popularCards]]
cardFloatPixmap = ':/GPPGUI/Resource/images/IARC_7+.svg.png'
cardPixmap = ':/GPPGUI/Resource/images/revn.png'
detailedText = '别说你是搞机翻的'
fromLocal = false
interactiveTips = 'Dir-A'
pathOrUrl = 'https://github.com/ZQF-ReVN'
subTitle = '拜见祖师爷'
title = 'ReVN'

