[package]
namespace = "gpp"
name = "cli"

[dependencies]
"gpp.core" = { path = "../GalTranslPP" }
"gpp.version" = { path = "../GPPVersion" }

[build-dependencies]
"gpp.build" = { path = "../mcpp-build-scripts/gpp-build", host-module = true }

[target.windows.build-dependencies]
"gpp.runtime-stage" = { path = "../mcpp-build-scripts/runtime-stage", tools = ["runtime_stage"] }

[profile.release]
opt = 3
debug = true
lto = true

[profile.fast-release]
opt = 0
debug = true
lto = false

[build]
default-profile = "release"
sources = [
  "ProgressBar.ixx",
  "TerminalController.ixx",
  "!x64/**",
  "!x86/**",
  "!ARM64/**"
]
module_extensions = [".ixx"]
include_dirs = [
  ".",
  "../3rdParty/pybind11/include"
]

[target.windows.build]
include_dirs = ["../3rdParty/pybind11/Python/include"]
defines = ["UNICODE", "_UNICODE", "_CONSOLE", "_CRT_SECURE_NO_WARNINGS",
  "WIN32_LEAN_AND_MEAN", "NOMINMAX",
  "_RANGES_",
  "SPDLOG_WCHAR_FILENAMES"]

[targets.GalTranslPP_CLI]
kind = "bin"
main = "GPPCLI.cpp"
windows_subsystem = "console"

[resources]
files = ["GPPCLI.rc"]
extra-inputs = ["GPPCLI.manifest"]
