[package]
namespace = "gpp"
name = "cli"

[dependencies]
"gpp.core" = { path = "../GalTranslPP" }
"gpp.version" = { path = "../GPPVersion" }

[build]
default-profile = "release"
sources = ["ProgressBar.ixx", "TerminalController.ixx"]
module_extensions = [".ixx"]
include_dirs = [
  ".",
  "../GalTranslPP",
  "../3rdParty/pybind11/include",
  "../3rdParty/pybind11/Python/include",
  "../vcpkg_installed/gpp-x64-windows-release/include"
]
ldflags = ["-L../3rdParty/pybind11/bin", "-lpython312", "-lpython3"]

[targets.GalTranslPP_CLI]
kind = "bin"
main = "GPPCLI.cpp"
windows_subsystem = "console"

[resources]
files = ["GPPCLI.rc"]
extra-inputs = ["GPPCLI.manifest"]
