[package]
namespace = "gpp"
name = "cli"

[dependencies]
"gpp.core" = { path = "../GalTranslPP" }
"gpp.version" = { path = "../GPPVersion" }

[build-dependencies]
"gpp.runtime-stage" = { path = "../mcpp-build-scripts/runtime-stage", tools = ["runtime_stage"] }

[profile.release]
opt = 3
debug = true
lto = true
strip = false
ldflags = ["-Wl,/DEBUG", "-Wl,/OPT:REF", "-Wl,/OPT:ICF", "-Wl,/INCREMENTAL:NO"]

[profile.fast-release]
opt = 0
debug = true
lto = false
strip = false
ldflags = ["-Wl,/DEBUG"]

[build]
default-profile = "release"
sources = ["ProgressBar.ixx", "TerminalController.ixx"]
module_extensions = [".ixx"]
include_dirs = [
  ".",
  "../GalTranslPP",
  "../3rdParty/pybind11/include",
  "../3rdParty/pybind11/Python/include",
  "../vcpkg_installed/gpp-x64-windows-release/include"
]
ldflags = ["-L../3rdParty/pybind11/bin", "-lpython312", "-lpython3"]

[targets.GalTranslPP_CLI]
kind = "bin"
main = "GPPCLI.cpp"
windows_subsystem = "console"

[resources]
files = ["GPPCLI.rc"]
extra-inputs = ["GPPCLI.manifest"]
