[[normalDict]]
org = 'あなひゃ'
rep = 'あなた'
isReg = false
priority = 0

[[normalDict]]
org = 'わたひ'
rep = '私'
isReg = false
priority = 0

[[normalDict]]
org = 'わらひ'
rep = '私'
isReg = false
priority = 0

[[normalDict]]
org = 'わらし'
rep = '私'
isReg = false
priority = 0

[[normalDict]]
org = 'ひょ'
rep = 'と'
isReg = false
priority = 0

[[normalDict]]
org = 'りゅ'
rep = 'る'
isReg = false
priority = 0

[[normalDict]]
org = 'しへぇ'
rep = 'して'
isReg = false
priority = 0

[[normalDict]]
org = 'しへっ'
rep = 'して'
isReg = false
priority = 0

[[normalDict]]
org = 'しひな'
rep = 'しいな'
isReg = false
priority = 0

[[normalDict]]
org = 'しひゃ'
rep = 'しちゃ'
isReg = false
priority = 0

[[normalDict]]
org = 'しゃま'
rep = '様'
isReg = false
priority = 0

[[normalDict]]
org = 'しゃみゃ'
rep = '様'
isReg = false
priority = 0

[[normalDict]]
org = 'しゃん'
rep = 'さん'
isReg = false
priority = 0

[[normalDict]]
org = 'しゅぎ'
rep = 'すぎ'
isReg = false
priority = 0

[[normalDict]]
org = 'しゅごひ	すごい'
rep = ''
isReg = false
priority = 0

[[normalDict]]
org = 'しゅごイ'
rep = 'すごい'
isReg = false
priority = 0

[[normalDict]]
org = 'しゅゴい'
rep = 'すごい'
isReg = false
priority = 0

[[normalDict]]
org = 'しゅご'
rep = 'すご'
isReg = false
priority = 0

[[normalDict]]
org = 'しゅきぃ	しゅき'
rep = ''
isReg = false
priority = 0

[[normalDict]]
org = 'しゅき'
rep = '好き'
isReg = false
priority = 0

[[normalDict]]
org = 'しなひ'
rep = 'しない'
isReg = false
priority = 0

[[normalDict]]
org = 'しぇいえき'
rep = '精液'
isReg = false
priority = 0

[[normalDict]]
org = 'しゅけべ'
rep = 'スケベ'
isReg = false
priority = 0

[[normalDict]]
org = 'しきゅ'
rep = '子宮'
isReg = false
priority = 0

[[normalDict]]
org = 'しゃれれ'
rep = 'されて'
isReg = false
priority = 0

[[normalDict]]
org = 'しゃれて'
rep = 'されて'
isReg = false
priority = 0

[[normalDict]]
org = 'しょこ'
rep = 'そこ'
isReg = false
priority = 0

[[normalDict]]
org = 'らい好き'
rep = '大好き'
isReg = false
priority = 0

[[normalDict]]
org = 'かみ様'
rep = '神様'
isReg = false
priority = 0

[[normalDict]]
org = 'ひんぽ'
rep = 'ちんぽ'
isReg = false
priority = 0

[[normalDict]]
org = 'ひんこ'
rep = 'ちんぽ'
isReg = false
priority = 0

[[normalDict]]
org = 'ひんひん'
rep = 'ちんぽ'
isReg = false
priority = 0

[[normalDict]]
org = 'ヒンポ'
rep = 'ちんぽ'
isReg = false
priority = 0

[[normalDict]]
org = 'きもち'
rep = '気持ち'
isReg = false
priority = 0

[[normalDict]]
org = 'きもひ'
rep = '気持ち'
isReg = false
priority = 0

[[normalDict]]
org = 'ぎもひ'
rep = '気持ち'
isReg = false
priority = 0

[[normalDict]]
org = 'ぎもぢい'
rep = '気持ち'
isReg = false
priority = 0

[[normalDict]]
org = 'きひゃ'
rep = 'きた'
isReg = false
priority = 0

[[normalDict]]
org = 'うれひい'
rep = '嬉しい'
isReg = false
priority = 0

[[normalDict]]
org = 'せーえき'
rep = '精液'
isReg = false
priority = 0

[[normalDict]]
org = 'せ～えき'
rep = '精液'
isReg = false
priority = 0

[[normalDict]]
org = 'じゃーめん'
rep = '精液'
isReg = false
priority = 0

[[normalDict]]
org = 'せーし'
rep = '精子'
isReg = false
priority = 0

[[normalDict]]
org = 'らかりゃ'
rep = 'だがら'
isReg = false
priority = 0

[[normalDict]]
org = 'らけれ'
rep = 'だけで'
isReg = false
priority = 0

[[normalDict]]
org = 'れふかりゃ'
rep = 'ですから'
isReg = false
priority = 0

[[normalDict]]
org = 'かりゃ'
rep = 'から'
isReg = false
priority = 0

[[normalDict]]
org = 'らめだがら'
rep = 'ダメだがら'
isReg = false
priority = 0

[[normalDict]]
org = 'らしへっ'
rep = '出して'
isReg = false
priority = 0

[[normalDict]]
org = 'らひへ'
rep = '出して'
isReg = false
priority = 0

[[normalDict]]
org = 'らひて'
rep = '出して'
isReg = false
priority = 0

[[normalDict]]
org = '、らして'
rep = '、出して'
isReg = false
priority = 0

[[normalDict]]
org = 'にらして'
rep = 'に出して'
isReg = false
priority = 0

[[normalDict]]
org = 'らしゃれ'
rep = '出され'
isReg = false
priority = 0

[[normalDict]]
org = 'らめらめ'
rep = 'ダメダメ'
isReg = false
priority = 0

[[normalDict]]
org = 'らめっ'
rep = 'ダメ'
isReg = false
priority = 0

[[normalDict]]
org = 'らめ、'
rep = 'ダメ、'
isReg = false
priority = 0

[[normalDict]]
org = 'らめ…'
rep = 'ダメ…'
isReg = false
priority = 0

[[normalDict]]
org = 'らめぇ'
rep = 'ダメ'
isReg = false
priority = 0

[[normalDict]]
org = 'らめ！'
rep = 'ダメ！'
isReg = false
priority = 0

[[normalDict]]
org = 'らめです'
rep = 'ダメです'
isReg = false
priority = 0

[[normalDict]]
org = 'らめなの'
rep = 'ダメなの'
isReg = false
priority = 0

[[normalDict]]
org = 'らめらの'
rep = 'ダメなの'
isReg = false
priority = 0

[[normalDict]]
org = 'なからし'
rep = '中出し'
isReg = false
priority = 0

[[normalDict]]
org = 'ながりゃ'
rep = 'ながら'
isReg = false
priority = 0

[[normalDict]]
org = 'なきゃに'
rep = '中に'
isReg = false
priority = 0

[[normalDict]]
org = 'あちゅい'
rep = '暑い'
isReg = false
priority = 0

[[normalDict]]
org = 'あちゅイ'
rep = '暑い'
isReg = false
priority = 0

[[normalDict]]
org = 'あちゅく'
rep = '暑く'
isReg = false
priority = 0

[[normalDict]]
org = 'あちゅあちゅ'
rep = 'あつあつ'
isReg = false
priority = 0

[[normalDict]]
org = 'あちゅし'
rep = '暑し'
isReg = false
priority = 0

[[normalDict]]
org = 'おぐに'
rep = '奥に'
isReg = false
priority = 0

[[normalDict]]
org = 'おいひい'
rep = '美味しい'
isReg = false
priority = 0

[[normalDict]]
org = 'おかひ'
rep = 'おかし'
isReg = false
priority = 0

[[normalDict]]
org = 'おしおき'
rep = 'お仕置き'
isReg = false
priority = 0

[[normalDict]]
org = 'もっろ'
rep = 'もっと'
isReg = false
priority = 0

[[normalDict]]
org = 'れひゅ'
rep = 'です'
isReg = false
priority = 0

[[normalDict]]
org = 'れしゅ'
rep = 'です'
isReg = false
priority = 0

[[normalDict]]
org = 'まひゅ'
rep = 'ます'
isReg = false
priority = 0

[[normalDict]]
org = 'えっひな'
rep = 'エッチな'
isReg = false
priority = 0

[[normalDict]]
org = '可愛がっれ'
rep = '可愛がって'
isReg = false
priority = 0

[[normalDict]]
org = '赤ひゃん'
rep = '赤ちゃん'
isReg = false
priority = 0

[[normalDict]]
org = '主ひゃん'
rep = '主ちゃん'
isReg = false
priority = 0

[[normalDict]]
org = 'でちゅ'
rep = 'です'
isReg = false
priority = 0

[[normalDict]]
org = 'けろ'
rep = 'けど'
isReg = false
priority = 0

[[normalDict]]
org = '恥じゅ'
rep = '恥ず'
isReg = false
priority = 0

[[normalDict]]
org = '恥ずかひ'
rep = '恥ずかし'
isReg = false
priority = 0

[[normalDict]]
org = 'かひい'
rep = 'かしい'
isReg = false
priority = 0

[[normalDict]]
org = '止まらなひ'
rep = '止まらない'
isReg = false
priority = 0

[[normalDict]]
org = 'トロけひゃ'
rep = '蕩けちゃ'
isReg = false
priority = 0

[[normalDict]]
org = 'トロけ'
rep = '蕩け'
isReg = false
priority = 0

[[normalDict]]
org = 'みるく'
rep = 'ミルク'
isReg = false
priority = 0

[[normalDict]]
org = 'まひゃ'
rep = 'また'
isReg = false
priority = 0

[[normalDict]]
org = 'イきゅ'
rep = 'イく'
isReg = false
priority = 0

[[normalDict]]
org = 'イっく'
rep = 'イく'
isReg = false
priority = 0

[[normalDict]]
org = 'イクぅ'
rep = 'イクぅ'
isReg = false
priority = 0

[[normalDict]]
org = 'イぐ'
rep = 'イく'
isReg = false
priority = 0

[[normalDict]]
org = 'れふっ'
rep = 'です'
isReg = false
priority = 0

[[normalDict]]
org = 'はげひ'
rep = '激しい'
isReg = false
priority = 0

[[normalDict]]
org = 'されへ'
rep = 'されて'
isReg = false
priority = 0

[[normalDict]]
org = 'イカしぇ'
rep = 'イカせ'
isReg = false
priority = 0

[[normalDict]]
org = 'イカしゃ'
rep = 'イカせ'
isReg = false
priority = 0

[[normalDict]]
org = 'たくひゃん'
rep = 'たくさん'
isReg = false
priority = 0

[[normalDict]]
org = 'いひょに'
rep = '一緒に'
isReg = false
priority = 0

[[normalDict]]
org = 'いっふぁい'
rep = 'いっぱい'
isReg = false
priority = 0

[[normalDict]]
org = 'みたひに'
rep = 'みたいに'
isReg = false
priority = 0

[[normalDict]]
org = 'かっひゃ'
rep = 'かった'
isReg = false
priority = 0

[[normalDict]]
org = 'ちょうらい'
rep = 'ちょうだい'
isReg = false
priority = 0

[[normalDict]]
org = 'ごしゅじんひゃま'
rep = 'ご主人様'
isReg = false
priority = 0

[[normalDict]]
org = 'ごしゅじん'
rep = 'ご主人'
isReg = false
priority = 0

[[normalDict]]
org = 'ごひゅいんふん'
rep = 'ご主人くん'
isReg = false
priority = 0

[[normalDict]]
org = 'ごしゅいん'
rep = 'ご主人'
isReg = false
priority = 0

[[normalDict]]
org = 'ごしゅりん'
rep = 'ご主人'
isReg = false
priority = 0

[[normalDict]]
org = 'ごしゅりんきゅん'
rep = 'ご主人くん'
isReg = false
priority = 0

[[normalDict]]
org = 'ごひゅりんはま'
rep = 'ご主人様'
isReg = false
priority = 0

[[normalDict]]
org = 'ごひゅりんひゃは'
rep = 'ご主人様'
isReg = false
priority = 0

[[normalDict]]
org = 'ごひゅりんひゃま'
rep = 'ご主人様'
isReg = false
priority = 0

[[normalDict]]
org = 'ごひゅりん'
rep = 'ご主人'
isReg = false
priority = 0

[[normalDict]]
org = 'ごひゅじんひゃみゃ'
rep = 'ご主人様'
isReg = false
priority = 0

[[normalDict]]
org = 'ごひゅじんきゅん'
rep = 'ご主人くん'
isReg = false
priority = 0

[[normalDict]]
org = 'ごひゅじん'
rep = 'ご主人'
isReg = false
priority = 0

[[normalDict]]
org = 'ご主人きゅん'
rep = 'ご主人くん'
isReg = false
priority = 0

[[normalDict]]
org = '主きゅん'
rep = '主くん'
isReg = false
priority = 0

[[normalDict]]
org = '主クン'
rep = '主くん'
isReg = false
priority = 0

[[normalDict]]
org = 'ご主人ひゃま'
rep = 'ご主人様'
isReg = false
priority = 0

[[normalDict]]
org = 'ありゅじ'
rep = '主'
isReg = false
priority = 0

[[normalDict]]
org = 'こにょまま'
rep = 'このまま'
isReg = false
priority = 0

[[normalDict]]
org = 'くれへっ'
rep = 'くれてっ'
isReg = false
priority = 0

[[normalDict]]
org = 'くらひゃイ'
rep = 'ください'
isReg = false
priority = 0

[[normalDict]]
org = 'くらさイ'
rep = 'ください'
isReg = false
priority = 0

[[normalDict]]
org = 'くらさい'
rep = 'ください'
isReg = false
priority = 0

[[normalDict]]
org = 'くらさぁい'
rep = 'ください'
isReg = false
priority = 0

[[normalDict]]
org = 'まらまら'
rep = 'またまた'
isReg = false
priority = 0

[[normalDict]]
org = '、まら'
rep = '、また'
isReg = false
priority = 0

[[normalDict]]
org = '…まら'
rep = '…また'
isReg = false
priority = 0

[[normalDict]]
org = 'にまら'
rep = 'にまた'
isReg = false
priority = 0

[[normalDict]]
org = 'もまら'
rep = 'もまた'
isReg = false
priority = 0

[[normalDict]]
org = 'れふ'
rep = 'です'
isReg = false
priority = 0

